# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: vitan.me
subtitle: ⁣⁣⁣Stay Hungry, Stay Foolish.
description: Vitan's personal website.
keywords: Coder,Linux,Web,Blog...
author: Vitan
author_link: https://vitan.me
language: zh-CN
  
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://vitan.me
root: /
permalink: posts/:title.html
permalink_defaults: :title/

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: downloads/code/*

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: true # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true

highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''

markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: false
    linkify: true
    typographer: true
    quotes: '“”‘’'

  plugins:
    - markdown-it-abbr
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-sub
    - markdown-it-sup
    - markdown-it-emoji
    - markdown-it-deflist
    - markdown-it-container
    - markdown-it-mark
        
  anchors:
    level: 1
    collisionSuffix: 'v'
    permalink: false
    permalinkClass: header-anchor
    permalinkSymbol: ""
    permalinkBefore: false

# Category & Tag
default_category: uncategorized
category_map:
tag_map:  

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

archive_generator:
  per_page: 0
  yearly: true
  monthly: false
  daily: false

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: icarus

lazyload:
  enable: false
  onlypost: false

# Google analytics
google_analytics: UA-144334903-1

# Google Adsense
google_adsense:
  id: ca-pub-2581760538335948

#Rss Sitemap
feed:
  type: atom
  path: /xml/atom.xml
sitemap:
  path: /xml/sitemap.xml

# 打赏
donate:
  enable: true
  donate_message: 赏
  alipay: /images/alipay.png
  wechat: /images/wechat.png

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: ssh://git@github.com/ivitan/ivitan.github.io.git
  branch: master